# see https://fly.io/docs/languages-and-frameworks/python/

app = "solana-bankingstage-dashboard"
# Tokyo, Japan
primary_region = "nrt"

[env]
  PORT = "8080"
  POOLED_DB_MAX_SIZE = 4

[http_service]
  internal_port = 8080
  force_https = true

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"
