# see https://fly.io/docs/languages-and-frameworks/python/

app = "solana-bankingstage-dashboard"
# Tokyo, Japan
primary_region = "nrt"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
